# Generated by Django 5.2.11 on 2026-02-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('HP', models.IntegerField()),
                ('AC', models.IntegerField()),
                ('CR', models.CharField(max_length=10)),
                ('speed', models.CharField(max_length=300)),
                ('stats', models.CharField(max_length=100)),
                ('skills', models.TextField()),
                ('attributes', models.TextField()),
                ('actions', models.TextField()),
                ('legendaryActions', models.TextField()),
                ('rangedAttack', models.BooleanField(default=False)),
                ('pack', models.CharField(max_length=100)),
            ],
        ),
    ]
