# Generated by Django 5.2.11 on 2026-03-06 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dndApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='XP',
            field=models.CharField(default='100', max_length=10),
        ),
    ]
