# Generated by Django 5.2.11 on 2026-03-17 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dndApp', '0002_monster_xp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('CR', models.CharField(blank=True, max_length=50)),
                ('XP', models.IntegerField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Monsters', models.ManyToManyField(blank=True, to='dndApp.monster')),
            ],
        ),
    ]
